"""Canonical day-by-day itinerary data.

Edit this file for schedule changes, then run ``python3 build_itineraries.py``.
Costs and full reservation records remain in build_costs.py and bookings.md.
"""

TRIP = {
    "title": "Bavaria · Salzburg · Vienna",
    "subtitle": "Summer 2026 Family Trip",
    "dates": "July 11–22, 2026",
    "travelers": "Family of 4",
}


def event(time, text, *, where=None, kind="plan"):
    item = {"time": time, "text": text, "kind": kind}
    if where:
        item["where"] = where
    return item


DAYS = [
    {
        "day": 0,
        "date": "Sat Jul 11",
        "title": "Travel to Munich",
        "location": "Washington, DC → Munich",
        "overnight": "In flight",
        "summary": "Depart IAD on UA 108; transatlantic overnight flight.",
        "events": [
            event(
                "5:30 PM",
                "Depart IAD on **UA 108** (United, nonstop, Boeing 787-8) — **BOOKED** (Conf. IKR3ZV).",
                where="Washington Dulles International Airport. Check the United app or airport boards for the departure terminal and gate on the day.",
                kind="transport",
            ),
            event("Overnight", "Transatlantic flight; scheduled arrival in Munich is 7:45 AM the next morning.", kind="transport"),
        ],
        "notes": ["Keep passports and the United confirmation accessible during the overnight flight."],
    },
    {
        "day": 1,
        "date": "Sun Jul 12",
        "title": "Arrive Munich",
        "location": "Munich",
        "overnight": "Munich — Adamstraße 4",
        "summary": "Arrive MUC; S-Bahn to Marienplatz; Bounce bag storage 10 AM–7 PM; Altstadt; check in at Adamstraße 4.",
        "events": [
            event(
                "7:45 AM",
                "Land at Munich Airport, clear immigration, collect bags, and take the S-Bahn into the city.",
                where="Follow the green S-Bahn signs to Flughafen München station. Take **S1 or S8 toward central Munich** and exit at Marienplatz; allow roughly 40–50 minutes plus airport formalities.",
                kind="transport",
            ),
            event(
                "10:00 AM",
                "Drop bags at **Bounce — KADO NAILS Nagel & Kosmetik Studio** — **BOOKED** (Ref. S69FQ16J).",
                where="Rindermarkt 6, Im Innenhof (courtyard, by the stairs), 80331 Munich, just off Marienplatz. Contact: +49 162 8804646 (Ralf Mlinaric).",
                kind="booking",
            ),
            event("~11:00 AM", "See the Neues Rathaus Glockenspiel at Marienplatz; it chimes at 11 AM and noon.", kind="activity"),
            event("Lunch", "**TBD.** Viktualienmarkt's regular market stalls are closed on Sundays.", kind="meal"),
            event("Afternoon", "Visit Frauenkirche and wander the Altstadt at an easy arrival-day pace.", kind="activity"),
            event(
                "7:00 PM",
                "Pick up bags from Bounce.",
                where="Return to KADO NAILS at Rindermarkt 6 before the 7 PM pickup time.",
                kind="booking",
            ),
            event(
                "Evening",
                "Travel to the apartment, check in with Lars, have a light dinner, and turn in early.",
                where="From Marienplatz take an S-Bahn one stop to München Hbf. Follow signs for **U1 toward Olympia-Einkaufszentrum**, exit at Rotkreuzplatz, then walk about 10 minutes to **Adamstraße 4, 80636 Munich**. Check-in is after 3 PM; host Lars: +49 162 2840104.",
                kind="transport",
            ),
        ],
        "notes": ["Buy an MVV group day ticket at the airport before boarding; confirm the best S1/S8 departure on the station display."],
    },
    {
        "day": 2,
        "date": "Mon Jul 13",
        "title": "Munich",
        "location": "Munich",
        "overnight": "Munich — Adamstraße 4",
        "summary": "Free morning; Mike's Classic Bike Tour 11:30 AM–3:30 PM; Bavarian dinner.",
        "events": [
            event("Morning", "Free time: sleep in, have breakfast, or wander nearby.", kind="flex"),
            event(
                "11:15 AM",
                "Arrive at the **Mike's Bike Tours meeting point**.",
                where="**Marienplatz 15**, entrance to the Toy Museum (Spielzeugmuseum) in the Altes Rathaus at the eastern end of the square. This is the smaller old tower, not the Neues Rathaus with the Glockenspiel. A McDonald's should be visible nearby.",
                kind="transport",
            ),
            event(
                "11:30 AM",
                "Classic Bike Tour departs — **BOOKED** (Booking #354406124); about four hours through the English Garden, Olympiapark, and city highlights. Helmets are provided.",
                where="If 0–10 minutes late, look near the Statue of Juliet by the tower. If 15+ minutes late, go directly to the shop at **Hochbrückenstrasse 10**, corner of Brauhausstrasse.",
                kind="booking",
            ),
            event("~3:30 PM", "Bike tour returns to central Munich.", kind="activity"),
            event("Evening", "Dinner at Hopferhouse for traditional Bavarian food.", kind="meal"),
        ],
        "notes": ["Both teens must bring valid student ID because the student rate was used for their tickets."],
    },
    {
        "day": 3,
        "date": "Tue Jul 14",
        "title": "Munich → Königssee",
        "location": "Munich → Schönau am Königssee",
        "overnight": "Villa Alpenrausch",
        "summary": "Nymphenburg Palace and park; collect bags; regional trains via Freilassing; taxi to Schönau (Bus 841 backup).",
        "events": [
            event(
                "~8:45 AM",
                "Leave packed bags with Lars after checkout and go to Nymphenburg Palace.",
                where="Walk about 15 minutes from Adamstraße 4, or take **Tram 17** from Rotkreuzplatz via Romanplatz to Schloss Nymphenburg. Checkout is by 11 AM; arrange in advance for Lars to hold bags until about 1:30 PM.",
                kind="transport",
            ),
            event("9:00–10:00 AM", "Nymphenburg Palace state rooms — **BOOKED** (Order #42616; entry from 9 AM).", where="Schloss Nymphenburg, 80638 München. Use the main palace entrance and keep all four combination tickets accessible.", kind="booking"),
            event("10:00–10:35 AM", "Marstallmuseum: royal carriages and the Nymphenburg Porcelain collection.", kind="activity"),
            event("10:35–11:30 AM", "Walk through the park to Amalienburg and visit the rococo hunting lodge; prioritize the silver Hall of Mirrors.", kind="activity"),
            event("11:30 AM–12:30 PM", "See remaining park castles if energy allows, or take a slow walk back along the canal.", kind="flex"),
            event("12:30–1:15 PM", "Lunch at Palmenhaus café in the Orangery.", kind="meal"),
            event("~1:15 PM", "Walk back to Adamstraße 4 and collect bags from Lars.", kind="transport"),
            event("Early afternoon", "Use the schedule buffer to extend lunch or relax before the train.", kind="flex"),
            event(
                "~2:30 PM",
                "Take Bus 51 toward München Hbf.",
                where="Board Bus 51 in the Rotkreuzplatz area and allow about 20 minutes. At München Hbf, follow departure boards for the booked regional train; the ticket lists tracks **Gl. 5–10**, so confirm the exact platform at the station.",
                kind="transport",
            ),
            event("3:47 PM", "Regional train departs München Hbf — **BOOKED** (Bayern-Ticket, Conf. 342448586457; Ticketcode GMYV89JG).", where="München Hbf, exact track within Gl. 5–10 to be confirmed on the departure board. Take the regional train toward Salzburg/Freilassing.", kind="transport"),
            event("5:34 PM", "Arrive Freilassing; make the 11-minute connection.", where="Follow station signs and departure boards for the 5:45 PM S-Bahn/regional service to Berchtesgaden Hbf.", kind="transport"),
            event("5:45 PM", "Train departs Freilassing for Berchtesgaden Hbf.", kind="transport"),
            event(
                "6:38 PM",
                "Arrive Berchtesgaden Hbf, take a taxi to Villa Alpenrausch, and check in. **Bus 841 is the backup.**",
                where="Default: use the taxi rank outside Berchtesgaden Hbf for **Villa Alpenrausch, Waldhauserstraße 29, 83471 Schönau am Königssee**. Backup: board **Bus 841** toward Königssee/Schönau and exit at the nearest stop. Host Philipp: +49 176 21421010. Check-in is from 4 PM.",
                kind="transport",
            ),
        ],
        "notes": ["The Bayern-Ticket covers the regional trains and backup Bus 841. Confirm the exact Munich platform and taxi availability on the day."],
    },
    {
        "day": 4,
        "date": "Wed Jul 15",
        "title": "Eagle's Nest + Salt Mine",
        "location": "Berchtesgaden area",
        "overnight": "Villa Alpenrausch",
        "summary": "Bus via Berchtesgaden to Obersalzberg; Eagle's Nest; afternoon salt mine.",
        "events": [
            event(
                "Morning",
                "Use the host-provided Berchtesgaden Guest Card to travel to the Obersalzberg departure point for Eagle's Nest.",
                where="From Villa Alpenrausch, walk about 2–5 minutes to **Fischmichllehen** on Waldhauserstraße (near the Am Köppelberg junction). Take RVO **843B toward ZOB/Berchtesgaden Hbf**. At the ZOB, transfer to RVO **838 toward Dokumentation Obersalzberg / Kehlstein Busabfahrt**. Show the Guest Card on both local buses and check the 2026 timetable/app for the best connection.",
                kind="transport",
            ),
            event("Morning departure TBD", "Take the **Kehlsteinhaus Bus (RVO line 849)** and elevator to the Eagle's Nest summit (1,834 m); allow 3–4 hours including the return.", where="Board line **849** at **Dokumentation Obersalzberg / Kehlstein Busabfahrt**. This mountain bus requires a separate paid ticket and is **not covered by the Guest Card**. We plan to buy same-day tickets at the departure point; arrive early and be prepared to wait for a later bus if the next departure is full. After the upper bus stop, walk through the tunnel to the elevator.", kind="activity"),
            event("Afternoon", "Visit the Berchtesgaden salt mine (about 1½ hours): mine train, underground salt lake, and wooden slide.", where="Return from Obersalzberg toward Berchtesgaden. Confirm the salt-mine entrance route and booked/selected admission time before leaving in the morning.", kind="activity"),
        ],
        "notes": ["Decision reminder: we intentionally chose not to prebook Kehlstein line 849 because we value the flexibility to decide based on weather and energy. We are optimistic that an early Wednesday walk-up will have space, but accept that we may need to wait or skip Eagle's Nest if buses are full. Ask the Airbnb host for the physical or digital Berchtesgaden Guest Card; it covers local lines 843B and 838, but not line 849. The salt mine also appears to have plenty of availability, so we do not plan to book it in advance; recheck shortly before the trip."],
    },
    {
        "day": 5,
        "date": "Thu Jul 16",
        "title": "Königssee + Obersee",
        "location": "Königssee",
        "overnight": "Villa Alpenrausch",
        "summary": "Bus to Königssee dock; electric boat to Salet; hike to Obersee and Rotbachfall; return by boat.",
        "events": [
            event("~9:00 AM", "Travel to the Königssee boat landing.", where="Take **Bus 841** from the Schönau area toward Königssee/Jennerbahn and follow signs to the lakeside boat ticket office and landing. Check the return sailing board before departing.", kind="transport"),
            event("~9:00–10:00 AM", "Take an electric boat to **Salet** at the south end of Königssee; the ride is about 50 minutes and passes St. Bartholomä.", where="Use the Königssee lakeside boat landing. Board the sailing specifically continuing to **Salet**, not one terminating at St. Bartholomä.", kind="transport"),
            event("Mid-morning", "Walk from Salet landing to Obersee (about 20 minutes).", kind="activity"),
            event("Late morning", "Continue toward Röthbachfall, about 30 minutes farther, conditions permitting.", kind="activity"),
            event("Midday", "Return to Salet landing and take the electric boat back to Königssee.", where="Allow a generous margin for the final return sailing; verify that day's last departure from Salet on arrival.", kind="transport"),
            event("Afternoon", "Free time in Schönau; keep the pace flexible after the hike.", kind="flex"),
        ],
        "notes": ["Carry water and weather layers. Boat times and trail conditions must be checked on the day."],
    },
    {
        "day": 6,
        "date": "Fri Jul 17",
        "title": "Travel to Salzburg",
        "location": "Schönau → Salzburg",
        "overnight": "Salzburg — Gstättengasse 25",
        "summary": "Checkout; taxi to Salzburg Bounce storage at 10:30 AM; Altstadt; pick up bags at 6 PM; apartment check-in.",
        "events": [
            event(
                "~9:45 AM",
                "Checkout and take a taxi to the Salzburg Bounce location; book the taxi the evening before through Taxizentrale Berchtesgaden.",
                where="Pickup: **Villa Alpenrausch, Waldhauserstraße 29, Schönau am Königssee**. Destination: **Cafe cubed sugar, Griesgasse 13, 5020 Salzburg**. Allow about 30 minutes under normal conditions and confirm pickup time directly with the taxi company.",
                kind="transport",
            ),
            event("10:30 AM", "Drop bags at **Bounce — Cafe cubed sugar (Altstadt)** — **BOOKED** (Ref. 543WH67Q).", where="**Griesgasse 13, 5020 Salzburg**, first floor. Storage is booked for four regular and four small bags until 6:00 PM. Show the booking code from the Bounce app to staff.", kind="booking"),
            event("Late morning", "Have lunch and begin exploring the Altstadt at an easy pace.", kind="meal"),
            event("Afternoon", "Explore the Altstadt: Getreidegasse, Mozart's birthplace exterior at No. 9, Salzburg Cathedral, and Residenzplatz.", kind="activity"),
            event("6:00 PM", "Pick up bags from Bounce.", where="Return to **Cafe cubed sugar, Griesgasse 13**, first floor, by the booked pickup time.", kind="booking"),
            event("~6:15 PM", "Walk to the Salzburg apartment and check in using the lockbox instructions — **BOOKED** (Conf. HM4NSFM9J3).", where="Big Flat in Historic Mozart House, **Gstättengasse 25, Altstadt, 5020 Salzburg**. Host Medimmo GmbH: +43 664 1313022. Formal check-in begins after 1:00 PM.", kind="transport"),
            event("Evening", "Easy dinner and settle in.", kind="meal"),
        ],
        "notes": ["Formal checkout from Villa Alpenrausch is by 11 AM. Keep both the Bounce code and Salzburg lockbox instructions available offline."],
    },
    {
        "day": 7,
        "date": "Sat Jul 18",
        "title": "Salzburg",
        "location": "Salzburg",
        "overnight": "Salzburg — Gstättengasse 25",
        "summary": "Fortress Hohensalzburg; Getreidegasse; Mirabell Gardens; St. Peter dinner.",
        "events": [
            event("Morning", "Ride the funicular to Fortress Hohensalzburg and explore the castle and viewpoints; allow about two hours.", where="Walk through the Altstadt to the **FestungsBahn valley station near Kapitelplatz**. Buy/scan tickets there and board the funicular uphill to the fortress.", kind="transport"),
            event("Midday", "Walk Getreidegasse and stop for lunch.", kind="meal"),
            event("Afternoon", "Visit Mirabell Gardens, then stroll along the Salzach.", where="Cross to the north side of the river for Mirabellplatz/Mirabell Gardens; return on foot via a central pedestrian bridge.", kind="activity"),
            event("Evening", "Dinner at St. Peter Stiftskeller; reservation still to be booked.", where="St. Peter's Abbey complex in the Altstadt. Add the confirmed reservation time and exact arrival instructions after booking.", kind="meal"),
        ],
        "notes": ["Fortress and dinner details remain flexible until reservations are finalized."],
    },
    {
        "day": 8,
        "date": "Sun Jul 19",
        "title": "Travel to Vienna",
        "location": "Salzburg → Vienna",
        "overnight": "Vienna — Operngasse",
        "summary": "WESTbahn 9:52 AM; Vienna Bounce storage; Old Town and KHM; apartment check-in.",
        "events": [
            event("~9:20 AM", "Checkout and travel to Salzburg Hbf.", where="Leave **Gstättengasse 25** by the 10 AM checkout deadline. Walk or take a taxi to **Salzburg Hauptbahnhof**; allow 15–20 minutes and arrive with time to check the platform.", kind="transport"),
            event("9:52 AM", "WESTbahn departs Salzburg Hbf — **BOOKED** (Conf. NAYRKY).", where="At Salzburg Hbf, use the departure board to confirm the WESTbahn platform for Vienna. Do not use the unwanted 9:07 PM ÖBB reservations.", kind="transport"),
            event("12:22 PM", "Arrive at Vienna Hbf and continue toward the Bounce location.", where="From **Südtiroler Platz–Hauptbahnhof**, take **U1 toward Leopoldau** to Karlsplatz, then walk toward Schikanedergasse. Verify service changes on the day and allow extra time with luggage.", kind="transport"),
            event("~12:45 PM", "Drop bags at **Bounce — Restaurant Beograd Wien** — **BOOKED** (Ref. 1X9XMXPG).", where="**Schikanedergasse 7, 1040 Vienna**, near Naschmarkt. The booking window begins at 12:30 PM; pickup is 5:30 PM.", kind="booking"),
            event("12:45–1:30 PM", "Lunch near Naschmarkt.", kind="meal"),
            event("1:45–2:45 PM", "Easy Old Town orientation: Stephansdom interior, Graben, Pestsäule, and the Hofburg area.", kind="activity"),
            event("3:00–4:30 PM", "Kunsthistorisches Museum: grand staircase, Egyptian collection, Kunstkammer, and selected Old Masters.", where="Maria-Theresien-Platz. Enter from the main square-facing entrance; confirm same-day hours before leaving lunch.", kind="activity"),
            event("4:45–5:15 PM", "Walk back toward the Bounce location.", kind="transport"),
            event("5:30 PM", "Pick up bags from Bounce.", where="Restaurant Beograd Wien, Schikanedergasse 7.", kind="booking"),
            event("~5:45 PM", "Walk to the Operngasse apartment and check in — **BOOKED** (Conf. HMT8SQRKMA).", where="Operngasse, city center near the Opera; use the exact Airbnb arrival instructions for the building entrance. Host Eva & Friends: +43 676 5249090. Check-in is after 4 PM.", kind="transport"),
            event("6:30–7:30 PM", "Dinner near Naschmarkt or in the 1st district.", kind="meal"),
            event("After dinner", "Optional short stroll around the Hofburg exterior or Ringstrasse, or call it early.", kind="flex"),
        ],
        "notes": ["This is the densest travel day. The Vienna apartment street number is only in the private Airbnb arrival instructions."],
    },
    {
        "day": 9,
        "date": "Mon Jul 20",
        "title": "Schönbrunn + Vienna Evening",
        "location": "Vienna",
        "overnight": "Vienna — Operngasse",
        "summary": "Naschmarkt breakfast; U4 to Schönbrunn; palace, gardens, maze, and Gloriette; evening Old Town stroll.",
        "events": [
            event("8:30–9:45 AM", "Breakfast at a Naschmarkt café stall and browse the market.", where="Walk from the Operngasse apartment to Naschmarkt; regular stalls are open Monday–Saturday.", kind="meal"),
            event("9:45–10:30 AM", "Take the U4 to Schönbrunn with a schedule buffer.", where="Enter **Karlsplatz U-Bahn station** and take **U4 toward Hütteldorf**. Exit at **Schönbrunn** and follow signs toward the palace entrance.", kind="transport"),
            event("10:30 AM–12:00 PM", "Schönbrunn Palace Grand Tour; timed admission still to be booked.", where="Use the visitor entrance shown on the final ticket and arrive before the assigned entry time.", kind="booking"),
            event("12:00–1:00 PM", "Formal gardens and a casual lunch or snack on site.", kind="meal"),
            event("1:00–2:00 PM", "Hedge Maze and Labyrinth.", kind="activity"),
            event("2:00–3:00 PM", "Walk up to the Gloriette for panoramic views.", kind="activity"),
            event("3:00–4:00 PM", "Café break and return to the apartment; protect this downtime in summer heat.", where="Return via **U4 Schönbrunn toward Heiligenstadt**, exiting at Karlsplatz.", kind="transport"),
            event("Late afternoon", "Rest at the apartment.", kind="flex"),
            event("Evening", "Dinner and a lit-up walk past the Opera House, Albertina terrace, Hofburg/Michaelerplatz, and an optional Ringstrasse section.", kind="activity"),
        ],
        "notes": ["Optional: add Tiergarten Schönbrunn only if everyone wants a much longer palace day."],
    },
    {
        "day": 10,
        "date": "Tue Jul 21",
        "title": "Belvedere + Prater",
        "location": "Vienna",
        "overnight": "Vienna — Operngasse",
        "summary": "Upper Belvedere; lunch; transit to Prater and Riesenrad; final dinner.",
        "events": [
            event("9:00–11:30 AM", "Upper Belvedere Palace: Klimt's *The Kiss*, Secessionist collection, and formal gardens; timed entry still to be booked.", where="Use the **Upper Belvedere** entrance shown on the final ticket, not Lower Belvedere. Confirm the best tram/walking route from Operngasse after the admission time is booked.", kind="booking"),
            event("12:00–1:00 PM", "Lunch near Belvedere or toward the 3rd district.", kind="meal"),
            event("1:30–2:30 PM", "Travel to Prater.", where="Current plan: **Tram 71** from the Belvedere area toward the Ringstrasse, then **U2 to Praterstern**. Recheck the exact transfer and service pattern shortly before the trip.", kind="transport"),
            event("~2:30–5:30 PM", "Ride the 1897 Riesenrad and explore the surrounding Wurstelprater amusement park.", where="From Praterstern follow signs toward **Wiener Riesenrad / Wurstelprater**.", kind="activity"),
            event("Evening", "Final dinner in the 1st district, last Ringstrasse stroll, and pack for departure.", kind="meal"),
        ],
        "notes": ["Finalize the Belvedere arrival route when the timed ticket is booked."],
    },
    {
        "day": 11,
        "date": "Wed Jul 22",
        "title": "Fly Home",
        "location": "Vienna → Washington, DC",
        "overnight": "Home",
        "summary": "Checkout; U4 to Wien Mitte; CAT to VIE; OS 41 nonstop to IAD.",
        "events": [
            event("~8:00 AM", "Checkout and leave for Wien Mitte; formal checkout deadline is 10 AM.", where="From Karlsplatz take **U4 toward Heiligenstadt** to **Landstraße/Wien Mitte**, or use a taxi if luggage makes the transfer impractical.", kind="transport"),
            event("~8:30 AM", "Take the CAT (City Airport Train) to Vienna Airport; ride time is about 16 minutes.", where="At **Wien Mitte**, follow CAT signs to the dedicated airport-train platform. Confirm the departure on the station display before boarding.", kind="transport"),
            event("10:50 AM", "Depart VIE on **OS 41** (Austrian Airlines nonstop, Boeing 767-300) — **BOOKED** (Conf. IKR3ZV).", where="Vienna International Airport. Check the Austrian/United app and airport boards for the terminal and gate; proceed directly to bag drop/security after the CAT.", kind="transport"),
            event("2:35 PM EDT", "Scheduled arrival at Washington Dulles (IAD).", kind="transport"),
        ],
        "notes": ["Keep passports and flight confirmation accessible. Recheck CAT and flight status the evening before departure."],
    },
]
