"""Canonical definitions for generated itinerary maps."""

MAPS = {
    "day1_airport_to_munich": {
        "title": "Day 1 transfer · Munich Airport to city center",
        "output": "map_images/day1_airport_to_munich.png",
        "alt": "OpenStreetMap showing the Day 1 S-Bahn transfer from Munich Airport to Marienplatz",
        "zoom": 10,
        "viewport": (760, 342),
        "output_size": (1200, 540),
        "center_offset": (0, 0),
        "places": [
            {
                "number": 1,
                "name": "Munich Airport",
                "address": "S1 or S8 from terminal station",
                "lat": 48.3537694,
                "lon": 11.7861263,
            },
            {
                "number": 2,
                "name": "Marienplatz",
                "address": "City-center arrival",
                "lat": 48.1371436,
                "lon": 11.5753989,
            },
        ],
    },
    "day1_munich": {
        "title": "Day 1 locations · Munich",
        "output": "map_images/day1_munich.png",
        "alt": "OpenStreetMap showing the Day 1 Munich stops in the Altstadt, at Rotkreuzplatz, and at the Airbnb",
        "zoom": 13,
        "viewport": (600, 270),
        "output_size": (1200, 540),
        "center_offset": (0, 0),
        "places": [
            {
                "number": 1,
                "name": "Altstadt / Bounce",
                "address": "Rindermarkt · Marienplatz · Frauenkirche",
                "lat": 48.1359411,
                "lon": 11.5744792,
            },
            {
                "number": 2,
                "name": "Rotkreuzplatz",
                "address": "U1 arrival / walk to Airbnb",
                "lat": 48.1540479,
                "lon": 11.5330186,
            },
            {
                "number": 3,
                "name": "Airbnb",
                "address": "Adamstraße 4",
                "lat": 48.1486807,
                "lon": 11.5481772,
            },
        ],
    },
    "day2_munich": {
        "title": "Day 2 locations · central Munich",
        "output": "map_images/day2_munich.png",
        "alt": "OpenStreetMap showing the Munich Airbnb, Mike's Bikes, and Hofbräuhaus",
        "zoom": 14,
        # Render at 2x the logical viewport size for sharp printing.
        "viewport": (600, 270),
        "output_size": (1200, 540),
        "center_offset": (0, -15),
        "places": [
            {
                "number": 1,
                "name": "Airbnb",
                "address": "Adamstraße 4",
                "lat": 48.1486807,
                "lon": 11.5481772,
            },
            {
                "number": 2,
                "name": "Mike's Bikes",
                "address": "Marienplatz 15",
                "lat": 48.1368932,
                "lon": 11.5769276,
            },
            {
                "number": 3,
                "name": "Hofbräuhaus",
                "address": "Platzl 9",
                "lat": 48.1376334,
                "lon": 11.5799788,
            },
        ],
    },
    "day3_munich_to_schonau": {
        "title": "Day 3 route · Munich to Schönau",
        "output": "map_images/day3_munich_to_schonau.png",
        "alt": "OpenStreetMap showing the Day 3 route from Munich through Freilassing and Berchtesgaden to Schönau am Königssee",
        "zoom": 8,
        "viewport": (600, 240),
        "output_size": (1200, 480),
        "center_offset": (0, 0),
        "places": [
            {
                "number": 1,
                "name": "Munich morning",
                "address": "Airbnb · Nymphenburg · München Hbf",
                "lat": 48.1407253,
                "lon": 11.5569426,
            },
            {
                "number": 2,
                "name": "Freilassing transfer",
                "address": "Freilassing Bahnhof",
                "lat": 47.8362676,
                "lon": 12.9779797,
            },
            {
                "number": 3,
                "name": "Berchtesgaden → Villa",
                "address": "Hbf → Waldhauserstraße 29",
                "lat": 47.6263889,
                "lon": 12.9994444,
            },
        ],
        "route": [
            (48.1407253, 11.5569426),
            (47.8362676, 12.9779797),
            (47.6263889, 12.9994444),
            (47.6006577, 12.9789388),
        ],
    },
    "day3_munich_before_train": {
        "title": "Day 3 · Munich before the train",
        "output": "map_images/day3_munich_before_train.png",
        "alt": "OpenStreetMap showing the Day 3 Munich stops before the train",
        "zoom": 14,
        "viewport": (920, 460),
        "output_size": (1520, 760),
        "center_offset": (0, -12),
        "places": [
            {
                "number": 1,
                "name": "Airbnb / bags",
                "address": "Adamstraße 4",
                "lat": 48.1486807,
                "lon": 11.5481772,
            },
            {
                "number": 2,
                "name": "Nymphenburg Palace",
                "address": "Main palace entrance",
                "lat": 48.1583251,
                "lon": 11.5032919,
            },
            {
                "number": 3,
                "name": "Marstallmuseum",
                "address": "Carriages and porcelain",
                "lat": 48.1565946,
                "lon": 11.5044675,
            },
            {
                "number": 4,
                "name": "Amalienburg",
                "address": "Palace park",
                "lat": 48.1561055,
                "lon": 11.5004034,
            },
            {
                "number": 5,
                "name": "Palmenhaus café",
                "address": "Lunch in the Orangery",
                "lat": 48.1592928,
                "lon": 11.4997920,
            },
            {
                "number": 6,
                "name": "München Hbf",
                "address": "3:47 PM regional train",
                "lat": 48.1407253,
                "lon": 11.5569426,
            },
        ],
        "route": [
            (48.1486807, 11.5481772),
            (48.1583251, 11.5032919),
            (48.1565946, 11.5044675),
            (48.1561055, 11.5004034),
            (48.1592928, 11.4997920),
            (48.1486807, 11.5481772),
            (48.1407253, 11.5569426),
        ],
    },
    "day4_berchtesgaden": {
        "title": "Day 4 · Wimbachklamm, salt mine & Berchtesgaden",
        "output": "map_images/day4_berchtesgaden.png",
        "alt": "Map showing the Day 4 route from the Schönau apartment through breakfast and bakery stops to Wimbachklamm, the salt mine, and central Berchtesgaden, with Eagle's Nest marked only as an optional audible",
        "tile_source": "esri_world_street",
        "zoom": 11,
        "viewport": (600, 270),
        "output_size": (1200, 540),
        "center_offset": (0, 0),
        "places": [
            {
                "number": 1,
                "name": "Villa Alpenrausch",
                "address": "Waldhauserstraße 29",
                "lat": 47.6006577,
                "lon": 12.9789388,
            },
            {
                "number": 2,
                "name": "Breakfast",
                "address": "Café Kaffeesatz · Artenreitring 5",
                "lat": 47.6005895,
                "lon": 12.9806889,
            },
            {
                "number": 3,
                "name": "Bakery / bus backup",
                "address": "Zechmeister · Rathaus Unterstein",
                "lat": 47.6049750,
                "lon": 12.9861945,
            },
            {
                "number": 4,
                "name": "Wimbachklamm trailhead",
                "address": "Wimbachbrücke · taxi / RVO 846",
                "lat": 47.6033333,
                "lon": 12.9247222,
            },
            {
                "number": 5,
                "name": "Salt mine",
                "address": "Salzbergwerk Berchtesgaden",
                "lat": 47.6376931,
                "lon": 13.0177454,
            },
            {
                "number": 6,
                "name": "Berchtesgaden center",
                "address": "Marktplatz · dinner",
                "lat": 47.6330556,
                "lon": 13.0022222,
            },
            {
                "number": 7,
                "name": "Eagle's Nest (optional)",
                "address": "Game-time audible only",
                "lat": 47.6114847,
                "lon": 13.0420597,
            },
        ],
        "route": [
            (47.6006577, 12.9789388),
            (47.6005895, 12.9806889),
            (47.6049750, 12.9861945),
            (47.6033333, 12.9247222),
            (47.6376931, 13.0177454),
            (47.6330556, 13.0022222),
        ],
    },
    "day5_koenigssee": {
        "title": "Day 5 route · Königssee & Obersee",
        "output": "map_images/day5_koenigssee.png",
        "alt": "OpenStreetMap showing the Day 5 route from Bäckerei Zechmeister and Rathaus Unterstein by bus to the Königssee boat landing, then by boat to Salet and on foot to Obersee and Röthbachfall",
        "tile_source": "esri_world_street",
        "zoom": 11,
        "viewport": (760, 340),
        "output_size": (1200, 540),
        "center_offset": (0, -15),
        "places": [
            {
                "number": 1,
                "name": "Breakfast / bus",
                "address": "Zechmeister · Rathaus Unterstein · 843B",
                "lat": 47.6049750,
                "lon": 12.9861945,
            },
            {
                "number": 2,
                "name": "Königssee landing",
                "address": "Seelände boat terminal",
                "lat": 47.5880308,
                "lon": 12.9888353,
            },
            {
                "number": 3,
                "name": "Salet landing",
                "address": "Boat turnaround point",
                "lat": 47.5251670,
                "lon": 12.9727240,
            },
            {
                "number": 4,
                "name": "Obersee",
                "address": "Fischunkelalm shore",
                "lat": 47.5127992,
                "lon": 12.9964639,
            },
            {
                "number": 5,
                "name": "Röthbachfall",
                "address": "Hike turnaround point",
                "lat": 47.5019447,
                "lon": 13.0121857,
            },
        ],
        "route": [
            (47.6049750, 12.9861945),
            (47.5880308, 12.9888353),
            (47.5251670, 12.9727240),
            (47.5127992, 12.9964639),
            (47.5019447, 13.0121857),
            (47.5127992, 12.9964639),
            (47.5251670, 12.9727240),
            (47.5880308, 12.9888353),
        ],
    },
    "day6_salzburg": {
        "title": "Day 6 locations · central Salzburg",
        "output": "map_images/day6_salzburg.png",
        "alt": "OpenStreetMap showing the Day 6 walking route through central Salzburg from bag storage to Altstadt sights and the apartment",
        "zoom": 15,
        "viewport": (600, 270),
        "output_size": (1200, 540),
        "center_offset": (0, 0),
        "places": [
            {
                "number": 1,
                "name": "Bounce / café",
                "address": "Griesgasse 13",
                "lat": 47.8005932,
                "lon": 13.0431902,
            },
            {
                "number": 2,
                "name": "Mozart's birthplace",
                "address": "Getreidegasse 9",
                "lat": 47.7999430,
                "lon": 13.0435536,
            },
            {
                "number": 3,
                "name": "Salzburg Cathedral",
                "address": "Domplatz",
                "lat": 47.7978459,
                "lon": 13.0466232,
            },
            {
                "number": 4,
                "name": "Residenzplatz",
                "address": "Altstadt",
                "lat": 47.7985232,
                "lon": 13.0461545,
            },
            {
                "number": 5,
                "name": "Apartment",
                "address": "Gstättengasse 25",
                "lat": 47.8014204,
                "lon": 13.0387388,
            },
        ],
        "route": [
            (47.8005932, 13.0431902),
            (47.7999430, 13.0435536),
            (47.7978459, 13.0466232),
            (47.7985232, 13.0461545),
            (47.8005932, 13.0431902),
            (47.8014204, 13.0387388),
        ],
    },
    "day7_salzburg": {
        "title": "Day 7 route · Salzburg",
        "output": "map_images/day7_salzburg.png",
        "alt": "OpenStreetMap showing the Day 7 Salzburg route from the apartment to the fortress funicular, Getreidegasse, Mirabell Gardens, and St. Peter",
        "zoom": 14,
        "viewport": (600, 270),
        "output_size": (1200, 540),
        "center_offset": (0, 0),
        "places": [
            {
                "number": 1,
                "name": "Apartment",
                "address": "Gstättengasse 25",
                "lat": 47.8014204,
                "lon": 13.0387388,
            },
            {
                "number": 2,
                "name": "Fortress funicular",
                "address": "Festungsbahn Talstation",
                "lat": 47.7964245,
                "lon": 13.0460338,
            },
            {
                "number": 3,
                "name": "Getreidegasse",
                "address": "Pedestrian street / lunch",
                "lat": 47.8000179,
                "lon": 13.0422373,
            },
            {
                "number": 4,
                "name": "Mirabell Gardens",
                "address": "Mirabellgarten",
                "lat": 47.8046561,
                "lon": 13.0416437,
            },
            {
                "number": 5,
                "name": "St. Peter dinner",
                "address": "Stiftskulinarium",
                "lat": 47.7969773,
                "lon": 13.0441606,
            },
        ],
        "route": [
            (47.8014204, 13.0387388),
            (47.7964245, 13.0460338),
            (47.8000179, 13.0422373),
            (47.8046561, 13.0416437),
            (47.7969773, 13.0441606),
        ],
    },
    "day8_salzburg_to_vienna": {
        "title": "Day 8 rail transfer · Salzburg to Vienna",
        "output": "map_images/day8_salzburg_to_vienna.png",
        "alt": "OpenStreetMap showing the Day 8 rail transfer from Salzburg Hauptbahnhof to Vienna Hauptbahnhof",
        "zoom": 7,
        "viewport": (600, 240),
        "output_size": (1200, 480),
        "center_offset": (0, 0),
        "places": [
            {
                "number": 1,
                "name": "Salzburg Hbf",
                "address": "9:52 AM WESTbahn departure",
                "lat": 47.8130618,
                "lon": 13.0458530,
            },
            {
                "number": 2,
                "name": "Vienna Hbf",
                "address": "12:22 PM arrival",
                "lat": 48.1849883,
                "lon": 16.3779391,
            },
        ],
    },
    "day8_vienna": {
        "title": "Day 8 locations · Vienna arrival",
        "output": "map_images/day8_vienna.png",
        "alt": "OpenStreetMap showing Day 8 Vienna stops from the main station through bag storage and Old Town to the museum and apartment area",
        "zoom": 13,
        "viewport": (660, 297),
        "output_size": (1200, 540),
        "center_offset": (0, 0),
        "places": [
            {
                "number": 1,
                "name": "Vienna Hbf",
                "address": "WESTbahn arrival / U1",
                "lat": 48.1849883,
                "lon": 16.3779391,
            },
            {
                "number": 2,
                "name": "Bounce / Beograd",
                "address": "Schikanedergasse 7",
                "lat": 48.1971297,
                "lon": 16.3638285,
            },
            {
                "number": 3,
                "name": "Stephansdom",
                "address": "Old Town orientation",
                "lat": 48.2084923,
                "lon": 16.3731269,
            },
            {
                "number": 4,
                "name": "Hofburg",
                "address": "Michaelerplatz area",
                "lat": 48.2076838,
                "lon": 16.3661951,
            },
            {
                "number": 5,
                "name": "Kunsthistorisches",
                "address": "Maria-Theresien-Platz",
                "lat": 48.2037395,
                "lon": 16.3617819,
            },
            {
                "number": 6,
                "name": "Apartment area",
                "address": "Operngasse · approximate",
                "lat": 48.1984016,
                "lon": 16.3662258,
            },
        ],
    },
    "day9_vienna_to_schoenbrunn": {
        "title": "Day 9 U4 transfer · Airbnb to Schönbrunn",
        "output": "map_images/day9_vienna_to_schoenbrunn.png",
        "alt": "OpenStreetMap showing the Day 9 trip from the Operngasse Airbnb area to Schönbrunn station via the U4",
        "zoom": 13,
        "viewport": (700, 315),
        "output_size": (1200, 540),
        "center_offset": (0, 0),
        "places": [
            {
                "number": 1,
                "name": "Airbnb area",
                "address": "Operngasse · walk to Karlsplatz",
                "lat": 48.1984016,
                "lon": 16.3662258,
            },
            {
                "number": 2,
                "name": "U4 Schönbrunn",
                "address": "Palace arrival / return station",
                "lat": 48.1860469,
                "lon": 16.3189401,
            },
        ],
    },
    "day9_schoenbrunn": {
        "title": "Day 9 locations · Schönbrunn",
        "output": "map_images/day9_schoenbrunn.png",
        "alt": "OpenStreetMap showing Day 9 stops at Schönbrunn station, the palace, formal gardens, maze, and Gloriette",
        "zoom": 15,
        "viewport": (800, 360),
        "output_size": (1200, 540),
        "center_offset": (0, 0),
        "places": [
            {
                "number": 1,
                "name": "U4 Schönbrunn",
                "address": "Arrival / return station",
                "lat": 48.1860469,
                "lon": 16.3189401,
            },
            {
                "number": 2,
                "name": "Schönbrunn Palace",
                "address": "Main visitor entrance",
                "lat": 48.1849894,
                "lon": 16.3115684,
            },
            {
                "number": 3,
                "name": "Formal gardens",
                "address": "Neptune Fountain area",
                "lat": 48.1814548,
                "lon": 16.3103792,
            },
            {
                "number": 4,
                "name": "Maze & Labyrinth",
                "address": "Irrgartenallee",
                "lat": 48.1825834,
                "lon": 16.3098062,
            },
            {
                "number": 5,
                "name": "Gloriette",
                "address": "Hilltop viewpoint",
                "lat": 48.1782674,
                "lon": 16.3087265,
            },
        ],
    },
    "day10_vienna": {
        "title": "Day 10 locations · Vienna",
        "output": "map_images/day10_vienna.png",
        "alt": "OpenStreetMap showing Day 10 Vienna stops from the Operngasse Airbnb area to Upper Belvedere, Schwarzenbergplatz, the Riesenrad, and the first district",
        "zoom": 13,
        "viewport": (720, 324),
        "output_size": (1200, 540),
        "center_offset": (0, 0),
        "places": [
            {
                "number": 1,
                "name": "Airbnb area",
                "address": "Operngasse · approximate",
                "lat": 48.1984016,
                "lon": 16.3662258,
            },
            {
                "number": 2,
                "name": "Upper Belvedere",
                "address": "Prinz-Eugen-Straße",
                "lat": 48.1915415,
                "lon": 16.3808882,
            },
            {
                "number": 3,
                "name": "Schwarzenbergplatz",
                "address": "Tram / Ringstrasse transfer area",
                "lat": 48.2009561,
                "lon": 16.3744079,
            },
            {
                "number": 4,
                "name": "Riesenrad / Prater",
                "address": "Via U2 Praterstern",
                "lat": 48.2167405,
                "lon": 16.3959085,
            },
            {
                "number": 5,
                "name": "First district",
                "address": "Stephansdom / final dinner area",
                "lat": 48.2084923,
                "lon": 16.3731269,
            },
        ],
    },
    "day11_vienna_airport": {
        "title": "Day 11 transfer · Vienna to airport",
        "output": "map_images/day11_vienna_airport.png",
        "alt": "OpenStreetMap showing the Day 11 transfer from the Operngasse and Karlsplatz area through Wien Mitte to Vienna Airport",
        "zoom": 11,
        "viewport": (600, 270),
        "output_size": (1200, 540),
        "center_offset": (0, 0),
        "places": [
            {
                "number": 1,
                "name": "Airbnb / Karlsplatz",
                "address": "Checkout · take U4",
                "lat": 48.2003906,
                "lon": 16.3695975,
            },
            {
                "number": 2,
                "name": "Wien Mitte",
                "address": "Transfer to CAT",
                "lat": 48.2056315,
                "lon": 16.3842468,
            },
            {
                "number": 3,
                "name": "Vienna Airport",
                "address": "CAT station / flight OS 41",
                "lat": 48.1202259,
                "lon": 16.5642737,
            },
        ],
    },
}
